CREATE TABLE IF NOT EXIST User(
    id SERIAL PRIMARY KEY,
    email TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE IF NOT EXIST Product(
    id SERIAL PRIMARY KEY,
    stand_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    priority VARCHAR(10) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (stand_id) REFERENCES Stand(id) ON DELETE CASCADE ON UPDATE CASCADE,
);

CREATE TABLE IF NOT EXIST Subscription(
    id SERIAL PRIMARY KEY,
);

CREATE TABLE IF NOT EXIST PriceCheckJob(
    id SERIAL PRIMARY KEY,
)

CREATE TABLE IF NOT EXIST PriceSnapshot(
    id SERIAL PRIMARY KEY,
)